In [17]:
import pandas as pd

melon_chart = pd.read_csv('./Data/2023-04-26-16_melon.csv', index_col='rank')
melon_chart

,title,singer,album
rank,,,
1,I AM,IVE (아이브),I've IVE
2,Kitsch,IVE (아이브),I've IVE
3,꽃,지수 (JISOO),ME
4,손오공,세븐틴 (SEVENTEEN),SEVENTEEN 10th Mini Album ‘FML'
5,파이팅 해야지 (Feat. 이영지),부석순 (SEVENTEEN),부석순 1st Single Album 'SECOND WIND'
...,...,...,...
96,"Young, Dumb, Stupid",NMIXX,expérgo
97,다시 사랑한다면,한동근,다시 사랑한다면
98,후유증 (Can We Go Back),NCT 도재정,Perfume - The 1st Mini Album
99,Off My Face,Justin Bieber,Justice (The Complete Edition)
100,Unholy,Sam Smith,Gloria

In [18]:
bugs_chart = pd.read_csv('./Data/2023-04-26-16_bugs.csv', index_col='rank')
bugs_chart

,title,singer,album
rank,,,
1,I AM,IVE (아이브),I've IVE
2,Kitsch,IVE (아이브),I've IVE
3,꽃,지수(JISOO),ME
4,Cupid,FIFTY FIFTY,The Beginning: Cupid
5,Ditto,NewJeans,NewJeans 'OMG'
...,...,...,...
96,자격지심 (Feat. ZICO),BE'O (비오),FIVE SENSES
97,Rising,tripleS (트리플에스),ASSEMBLE
98,I Don't Understand But I Luv U,세븐틴(SEVENTEEN),SEVENTEEN 10th Mini Album ‘FML'
99,Inspiration (feat. Beenzino),태양,Down to Earth
100,그댄 행복에 살텐데 (2022),최유리,그댄 행복에 살텐데 (2022)

In [19]:
genie_chart = pd.read_csv('./Data/2023-04-26-16_genie.csv', index_col='rank')
genie_chart[:100]

,title,singer,album
rank,,,
1,I AM,IVE (아이브),I've IVE
2,Kitsch,IVE (아이브),I've IVE
3,꽃,지수 (JISOO),ME
4,Ditto,NewJeans,NewJeans 'OMG'
5,Hype boy,NewJeans,NewJeans 1st EP 'New Jeans'
...,...,...,...
96,Rush Hour (Feat. j-hope of BTS),Crush,Rush Hour
97,밤하늘의 별을 (2020),경서,밤하늘의 별을 (2020)
98,너의 번호를 누르고 (Prod. by 영화처럼),#안녕,너의 번호를 누르고
99,Off My Face,Justin Bieber,Justice
100,신호등,이무진,신호등